# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    outline: none !important; \n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setStyleSheet("QStackedWidget QWidget#homePage, QStackedWidget QWidget#listPage, QStackedWidget QWidget#detailPage, QStackedWidget QWidget#aboutPage {\n"
"background: qlineargradient( x1:0 y1:0, x2:1 y2:0, stop:0 #acb6e5,  stop:1 #86fde8);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setStyleSheet("")
        self.homePage.setObjectName("homePage")
        self.label = QtWidgets.QLabel(self.homePage)
        self.label.setGeometry(QtCore.QRect(0, 80, 800, 80))
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 48px;\n"
"color: #2d1299;\n"
"font-weight: bold;")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.homePage)
        self.widget.setGeometry(QtCore.QRect(290, 250, 220, 240))
        self.widget.setStyleSheet("QPushButton {\n"
"    background: qlineargradient( x1:0 y1:0, x2:1 y2:0, stop:0 #2d1299,  stop:1 #2980b9);\n"
"    padding: 10px 8px 12px 8px;\n"
"    font-size: 24px;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient( x1:0 y1:0, x2:1 y2:0, stop:0 #8e2de2,  stop:1 #4a00e0);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contactListBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.contactListBtn.setFont(font)
        self.contactListBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactListBtn.setStyleSheet("")
        self.contactListBtn.setObjectName("contactListBtn")
        self.verticalLayout_2.addWidget(self.contactListBtn)
        self.aboutUsBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.aboutUsBtn.setFont(font)
        self.aboutUsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutUsBtn.setObjectName("aboutUsBtn")
        self.verticalLayout_2.addWidget(self.aboutUsBtn)
        self.exitBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.exitBtn.setFont(font)
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout_2.addWidget(self.exitBtn)
        self.label_11 = QtWidgets.QLabel(self.homePage)
        self.label_11.setGeometry(QtCore.QRect(370, 160, 64, 64))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("assets/icons/contact.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.homePage)
        self.listPage = QtWidgets.QWidget()
        self.listPage.setObjectName("listPage")
        self.label_2 = QtWidgets.QLabel(self.listPage)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 800, 51))
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 30px;\n"
"color: #2d1299;\n"
"font-weight: bold;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QWidget(self.listPage)
        self.listWidget.setGeometry(QtCore.QRect(100, 99, 600, 420))
        self.listWidget.setStyleSheet("QWidget#listWidget {\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #fff;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.listWidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.listWidget)
        self.frame.setStyleSheet("font-size: 16px;\n"
"color: #333;\n"
"font-weight: bold;")
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 9)
        self.verticalLayout.addWidget(self.frame)
        self.listScrollWrapper = QtWidgets.QScrollArea(self.listWidget)
        self.listScrollWrapper.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QScrollBar:vertical {              \n"
"    /*border: 1px solid #999999;*/\n"
"    border-radius: 5px;\n"
"    background: transparent;\n"
"    width: 12px;    \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #f27d85;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.listScrollWrapper.setWidgetResizable(True)
        self.listScrollWrapper.setObjectName("listScrollWrapper")
        self.listScrollArea = QtWidgets.QWidget()
        self.listScrollArea.setGeometry(QtCore.QRect(0, 0, 570, 364))
        self.listScrollArea.setObjectName("listScrollArea")
        self.frame_4 = QtWidgets.QFrame(self.listScrollArea)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 531, 81))
        self.frame_4.setStyleSheet("QFrame#frame_4 {\n"
"    border-bottom: 1px solid #ccc;\n"
"}")
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setContentsMargins(11, 0, 0, 8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setMinimumSize(QtCore.QSize(64, 64))
        self.label_15.setMaximumSize(QtCore.QSize(64, 64))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.widget_6 = QtWidgets.QWidget(self.frame_4)
        self.widget_6.setMinimumSize(QtCore.QSize(383, 71))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.widget_6)
        self.label_16.setMaximumSize(QtCore.QSize(64, 64))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("alexis_barnett_sm.png"))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget_6)
        self.label_17.setMinimumSize(QtCore.QSize(318, 0))
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.horizontalLayout_3.setStretch(2, 8)
        self.listScrollWrapper.setWidget(self.listScrollArea)
        self.verticalLayout.addWidget(self.listScrollWrapper)
        self.label_10 = QtWidgets.QLabel(self.listPage)
        self.label_10.setGeometry(QtCore.QRect(115, 140, 570, 1))
        self.label_10.setStyleSheet("border-top: 2px solid #333;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.listBackBtn = QtWidgets.QPushButton(self.listPage)
        self.listBackBtn.setGeometry(QtCore.QRect(300, 535, 200, 28))
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        self.listBackBtn.setFont(font)
        self.listBackBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listBackBtn.setStyleSheet("QPushButton {\n"
"font-size: 20px;\n"
"color: #2d1299;\n"
"background-color: none;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color: #8e2de2;\n"
"}")
        self.listBackBtn.setObjectName("listBackBtn")
        self.stackedWidget.addWidget(self.listPage)
        self.detailPage = QtWidgets.QWidget()
        self.detailPage.setStyleSheet("")
        self.detailPage.setObjectName("detailPage")
        self.detailBackBtn = QtWidgets.QPushButton(self.detailPage)
        self.detailBackBtn.setGeometry(QtCore.QRect(289, 532, 221, 28))
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        self.detailBackBtn.setFont(font)
        self.detailBackBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detailBackBtn.setStyleSheet("font-size: 20px;\n"
"color: #2d1299;\n"
"background-color: none;\n"
"border: none;")
        self.detailBackBtn.setObjectName("detailBackBtn")
        self.detailWrapper = QtWidgets.QWidget(self.detailPage)
        self.detailWrapper.setGeometry(QtCore.QRect(120, 57, 560, 461))
        self.detailWrapper.setStyleSheet("QWidget#detailWrapper {\n"
"    background-color: #fff;\n"
"    border-radius: 15px;\n"
"}")
        self.detailWrapper.setObjectName("detailWrapper")
        self.detailImg = QtWidgets.QLabel(self.detailWrapper)
        self.detailImg.setGeometry(QtCore.QRect(150, 20, 260, 260))
        self.detailImg.setStyleSheet("border: 1px solid #ccc;\n"
"border-radius: 20px;")
        self.detailImg.setText("")
        self.detailImg.setPixmap(QtGui.QPixmap("alexis_barnett.png"))
        self.detailImg.setScaledContents(True)
        self.detailImg.setObjectName("detailImg")
        self.detailName = QtWidgets.QLabel(self.detailWrapper)
        self.detailName.setGeometry(QtCore.QRect(0, 297, 560, 51))
        self.detailName.setStyleSheet("font-size: 28px;\n"
"color: #2d1299;\n"
"font-weight: bold;")
        self.detailName.setAlignment(QtCore.Qt.AlignCenter)
        self.detailName.setObjectName("detailName")
        self.widget_3 = QtWidgets.QWidget(self.detailWrapper)
        self.widget_3.setGeometry(QtCore.QRect(50, 344, 460, 48))
        self.widget_3.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("assets/icons/phone.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.detailPhone = QtWidgets.QLabel(self.widget_3)
        self.detailPhone.setStyleSheet("font-weight: bold;")
        self.detailPhone.setObjectName("detailPhone")
        self.horizontalLayout_2.addWidget(self.detailPhone)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.detailMail = QtWidgets.QLabel(self.widget_3)
        self.detailMail.setStyleSheet("font-weight: bold;")
        self.detailMail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detailMail.setObjectName("detailMail")
        self.horizontalLayout_2.addWidget(self.detailMail)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setMaximumSize(QtCore.QSize(32, 32))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("assets/icons/email.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.widget_5 = QtWidgets.QWidget(self.detailWrapper)
        self.widget_5.setGeometry(QtCore.QRect(150, 280, 260, 31))
        self.widget_5.setStyleSheet("font-size: 16px;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 2, 0, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setStyleSheet("font-weight: bold;")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.detailID = QtWidgets.QLabel(self.widget_5)
        self.detailID.setObjectName("detailID")
        self.horizontalLayout_4.addWidget(self.detailID)
        self.detailBio = QtWidgets.QLabel(self.detailWrapper)
        self.detailBio.setGeometry(QtCore.QRect(50, 400, 460, 40))
        self.detailBio.setStyleSheet("")
        self.detailBio.setAlignment(QtCore.Qt.AlignCenter)
        self.detailBio.setWordWrap(True)
        self.detailBio.setObjectName("detailBio")
        self.stackedWidget.addWidget(self.detailPage)
        self.aboutPage = QtWidgets.QWidget()
        self.aboutPage.setObjectName("aboutPage")
        self.label_4 = QtWidgets.QLabel(self.aboutPage)
        self.label_4.setGeometry(QtCore.QRect(0, 30, 800, 51))
        font = QtGui.QFont()
        font.setFamily("SVN-Cookies")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size: 30px;\n"
"color: #2d1299;\n"
"font-weight: bold;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.aboutPage)
        self.widget_2.setGeometry(QtCore.QRect(170, 130, 120, 80))
        self.widget_2.setStyleSheet("QWidget#listWidget {\n"
"    background-color: #fff;\n"
"    border-radius: 15px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.stackedWidget.addWidget(self.aboutPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contact List"))
        self.label.setText(_translate("MainWindow", "Digital Contact List"))
        self.contactListBtn.setText(_translate("MainWindow", "Contact List"))
        self.aboutUsBtn.setText(_translate("MainWindow", "About Us"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "Contact List"))
        self.label_8.setText(_translate("MainWindow", "ID"))
        self.label_9.setText(_translate("MainWindow", "Name"))
        self.label_15.setText(_translate("MainWindow", "C100000"))
        self.label_17.setText(_translate("MainWindow", "Alexandir gaga ehehehehe"))
        self.listBackBtn.setText(_translate("MainWindow", "Back to Home"))
        self.detailBackBtn.setText(_translate("MainWindow", "Back to Contact List"))
        self.detailName.setText(_translate("MainWindow", "Alexandir gaga ehehehehe"))
        self.detailPhone.setText(_translate("MainWindow", "01234567890"))
        self.detailMail.setText(_translate("MainWindow", "aaaaaaacdef@gmail.com"))
        self.label_7.setText(_translate("MainWindow", "ID:"))
        self.detailID.setText(_translate("MainWindow", "C1"))
        self.detailBio.setText(_translate("MainWindow", "Hello motherfucker, hehehe hahaha, one two three. ABC DEF XGHSAD ASDA DASD asd asdas qwe q asdas da"))
        self.label_4.setText(_translate("MainWindow", "About Us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
